{% set name = "sRNA" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 10f4991d93dbd7a3a4d7f2fcc83faf5ae8203349655ddac0098c71acc59216db

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - folium
    - ipyleaflet
    - pyshp
    - python >=3.6
    - bowtie 1.2.3
    - cutadapt 2.6
    - findadapt
    - tDRnamer
test:
  imports:
    - sRNA

about:
  home: "https://github.com/labcbb"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for sncRNA quantification"
  doc_url: https://geodemo.gishub.org
  dev_url: https://github.com/labcbb

extra:
  recipe-maintainers:
    - giswqs
