# config.yaml 
# input path
sample_list: "sample.txt" # path to sample list file, with each line in the file writing the complete path of a fastq file

# output path 
outdir: "results" #If you need to generate the folder in the specified path, you need to modify it to the specified path

# sRNA base directory
# If the config.yaml and snakemake file locates in sRNA-main directory, base_dir should be ./
# Other wise, set the config.yaml absolute path.
base_dir: "./"

# Reference sequence and index path（If you are not in the sRNA-main folder, an absolute path is required）
INDEX_BT: base_dir + "sRNA-index/miRNA/mature_ref"
INDEX_pre_BT: base_dir + "sRNA-index/premiRNA/premirna_index/premirna"
INDEX: base_dir + "sRNA-index/tDR/tDR_55"
INDEX_rRNA_BT: base_dir + "sRNA-index/rRF/rRNA.flank"
INDEX_snoRNA_BT: base_dir + "sRNA-index/sncRNA/other.sncRNA"
tDR_file: base_dir + "sRNA-index/tDR/tDR_55.fa"
MINTplate: base_dir + "MINTplates.py"

# tools path（If environment variables have been configured in the user environment, you do not need to write absolute paths）
bowtie: "bowtie"
samtools: "samtools"
cutadapt: "cutadapt"
fastqc: "fastqc"
multiqc: "multiqc"
findadapt: "findadapt"

# Enable/disable rules（"true" or "false"）
cutadapt_enabled: true # Is it necessary to use cutadapt to join the joints

# Whether to tDR variants（"yes" or "no"）
merge_variants: "yes"  # Is it necessary to display the tDR variant
