# config.yaml 
# Data path
sample_list: "sample.txt" # Sample list file, with each line in the file writing the complete path of a fastq file

# output path 
outdir: "results" #If you need to generate the folder in the specified path, you need to modify it to the specified path

# Reference sequence and index path（If you are not in the sRNA-main folder, an absolute path is required）
INDEX_BT: "sRNA-index/miRNA/mature_ref"
INDEX_pre_BT: "sRNA-index/premiRNA/premirna_index/premirna"
INDEX: "sRNA-index/tDR/tDR_55"
INDEX_rRNA_BT: "sRNA-index/rRF/rRNA.flank"
INDEX_snoRNA_BT: "sRNA-index/sncRNA/other.sncRNA"
tDR_file: "sRNA-index/tDR/tDR_55.fa"
MINTplate: "MINTplates.py"

# tools path（If environment variables have been configured in the user environment, you do not need to write absolute paths）
bowtie: "bowtie"
samtools: "samtools"
cutadapt: "cutadapt"
fastqc: "fastqc"
multiqc: "multiqc"
findadapt: "findadapt"

# Enable/disable rules（"true" or "false"）
cutadapt_enabled: true # Is it necessary to use cutadapt to join the joints

# Whether to tDR variants（"yes" or "no"）
merge_variants: "yes"  # Is it necessary to display the tDR variant
